version: '3.4'
services:
  postgres:
    container_name: 'find-location-postgres'
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hardpassword
      - POSTGRES_USER=find-location-user
      - POSTGRES_MULTIPLE_DATABASES="find-location-db","find-location-db-test"
    volumes:
      - ./tools/docker/entrypoint:/docker-entrypoint-initdb.d
      - 'dbdata:/var/lib/postgresql/data'

  backend:
    container_name: 'geo-backend'
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
    - .env
    environment:
      DATABASE_URL: postgres://find-location-user:hardpassword@postgres:5432/find-location-db

volumes:
  dbdata:
    name: find-location-volume

    