name: CI/CD

on: #workflow se pokrece kad pushujem na branch
  push:
    branches:
      - deploy
      - main
      - develop  
  pull_request:
    branches:
      - deploy
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services: #Postgres servis za testove
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Gandijeva85
          POSTGRES_DB: geotagger_test
        options: >-
          --health-cmd "pg_isready -U postgres -d geotagger_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository #GitHub Actions uzima moj kod
        uses: actions/checkout@v3

      - name: Setup Node.js #Koristi verziju Noda-a koju imam lokalno
        uses: actions/setup-node@v3
        with:
          node-version: 20  # ili verzija koju koristim lokalno

      - name: Install dependencies #npm install
        run: npm install

      - name: Generate Prisma Client #vazno za Prisma, inace build nece raditi
        run: npx prisma generate

      - name: Build NestJS project #npm run build kampajlira TS u JS
        run: npm run build

      - name: Run e2e tests #pokrece e2e testove sa postavljenim env varijablama
        env:
          DATABASE_URL: "postgresql://postgres:Gandijeva85@localhost:5432/geotagger_test"
          JWT_SECRET: testsecret
        run: npm run test:e2e 